# Generated by Django 5.0.6 on 2024-05-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('national_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('agreed_to_waiver', models.BooleanField(default=False)),
            ],
        ),
    ]
