# Generated by Django 5.0.6 on 2024-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
