# Generated by Django 5.0.6 on 2024-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=15)),
                ('home_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('waiter_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
