# Generated by Django 5.0.6 on 2024-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0006_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='room_images/')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
