# Generated by Django 5.0.6 on 2024-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0009_mpesatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('membership_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10)),
            ],
        ),
    ]
