# Generated by Django 5.0.6 on 2024-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_email', models.EmailField(max_length=254)),
                ('seconder_userid', models.CharField(max_length=100)),
                ('seconder_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary_range', models.CharField(max_length=100)),
            ],
        ),
    ]
