# Generated by Django 5.0.6 on 2024-06-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_proposed_email_proposed_user_alter_proposed_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_email', models.EmailField(max_length=254)),
                ('seconder_userid', models.CharField(max_length=100)),
                ('seconder_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary_range', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_email', models.EmailField(max_length=254)),
                ('seconder_userid', models.CharField(max_length=100)),
                ('seconder_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary_range', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
